
 select PK_CODIGOLIBRO, count(*)
  from LIBROS
  where PK_CODIGOLIBRO = 'LB005'
  group by all PK_CODIGOLIBRO;

  
 select  TITULO from LIBROS
 INNER JOIN AUTORESXLIBRO
 on LIBROS.PK_CODIGOLIBRO = AUTORESXLIBRO.FK_CODIGOLIBRO
 where LIBROS.PK_CODIGOLIBRO = 'LB005'
select APELLIDOS,NOMBRECOMPLETO, PAISORIGEN from AUTORES
 INNER JOIN AUTORESXLIBRO
 on  AUTORES.PK_CODIGOAUTOR = AUTORESXLIBRO.FK_CODIGOAUTOR
 where AUTORESXLIBRO.FK_CODIGOLIBRO = 'LB005'
 order by APELLIDOS desc;

  select  TITULO from LIBROS
 INNER JOIN AUTORESXLIBRO
 on LIBROS.PK_CODIGOLIBRO = AUTORESXLIBRO.FK_CODIGOLIBRO 
select APELLIDOS,NOMBRECOMPLETO, PAISORIGEN from AUTORES
 INNER JOIN AUTORESXLIBRO
 on  AUTORES.PK_CODIGOAUTOR = AUTORESXLIBRO.FK_CODIGOAUTOR
 order by APELLIDOS desc;
 
 
 select * from LIBROS
 where (PUBLICACION >=2017) AND (PUBLICACION <= 2020)
 order by PUBLICACION asc;

 select ESTADOSOLICITUD from EJEMPLARES
 INNER JOIN LIBROS
 on EJEMPLARES.FK_CODIGOLIBRO = LIBROS.PK_CODIGOLIBRO
 where EJEMPLARES.ESTADOSOLICITUD = 'Reservado'
 select TITULO from LIBROS
 INNER JOIN EJEMPLARES
 on EJEMPLARES.FK_CODIGOLIBRO = LIBROS.PK_CODIGOLIBRO
 where EJEMPLARES.ESTADOSOLICITUD = 'Reservado'
 

 select NOMBRE from EDITORIALES
  INNER JOIN LIBROS
  on EDITORIALES.PK_CODIGOEDITORIAL = LIBROS.FK_CODIGOEDITORIAL
  where EDITORIALES.NOMBRE = 'Angosta'
select TITULO from LIBROS
INNER JOIN EDITORIALES
on EDITORIALES.PK_CODIGOEDITORIAL = LIBROS.FK_CODIGOEDITORIAL
  where EDITORIALES.NOMBRE = 'Angosta'